### ISSUE TITLE
WebAsm under iOS

### ISSUE THREAD

**Issue by AlexanderARodin** [mrDIMAS/tinyaudio#6]
I'm developing simple app mostly targeting to be used on WASM platform.
And have discovered an Issue with iOS. It just doesn't play.
Other platforms like Windows, MacOS, Android work just fine, iOS doesn’t.
As far I understand, WASM app under iOS gets only 2 callbacks for audio buffer filling. And after that callbacks disappear.

How can it be fixed or what is work-around maybe for that case?

Thank you in advance,
A

**Comment by mrDIMAS** [comment]
Am I correct that you're running WebAssembly build on top of iOS? If so, then you're might be getting the same issue as [here](https://stackoverflow.com/questions/46249361/cant-get-web-audio-api-to-work-with-ios-11-safari) - in other words you need to initialize tinyaudio only after some tap in your app.

**Comment by AlexanderARodin** [comment]
Correct. I test wasm-app on a few platforms. But issue appears only with iOS.
The link looks partially similar but:
1) it is about **input** therefore iOS may require some additional confirmations to allow it
2) it is about Safari only. I tested Opera and it has the same result.
3) I keep in mind recommendation 'only after some user tap'. To implement that my app launchs tinyaudio after some setup dialog has ended. Maybe it should be html-button instead of wasm-button. is there difference?

Probably I need to perform a couple more tests for researching.

**Comment by mrDIMAS** [comment]
What's the output of the developer console? It could shed some light why this happens. 

In the WebAssembly [example](https://github.com/mrDIMAS/tinyaudio/blob/main/wasm-examples/main.js#L7), it initializes the crate only after a button click. This is standard button, not sure what wasm-button is though.

**Comment by AlexanderARodin** [comment]
Thank you for the example. I'll try it too.
What about *developer console*. I'm not sure there is such a thing like *developer console* in iOS Safari. I'll check it too.

**Comment by AlexanderARodin** [comment]
Finally, day spent but I could not integrate the example code to my project because it's auto-build by **trunk**. And **trunk** produce too many changes automatically. Probably I will need to exclude trunk in final toolchain. Or have learn manage it more deeply.

Thank you for suggestions.
I'll have to return for testing later.

**Comment by AlexanderARodin** [comment]
if you are curios, I've performed a bunch of tests on iOS simulator with different version iOS. Also checked conclusion on real iPhones and iPads.
Outcomes are:
1. some analog simplified analog of the Example works fine.
2. iOS 16.4+ behaves mostly like PC/Mac browsers. except one thing - 'wasm-button' generated by **gui** doesn't create required effects on real devices but works good on simulator (same as on Mac/PC).
3. iOS 15.5- requires 'work-around' like into the Example in tinyaudio. Without that 'work-around' it may work too but it requires ability repeat button-click processing. 'wasm-button' via **gui** doesn't work even on simulator either.
