### ISSUE TITLE
WASM drop() doesn't close/clean up the audio context

### ISSUE THREAD

**Issue by dustinbowers** [mrDIMAS/tinyaudio#7]
When a `let device = run_output_device(params, data_callback)` is dropped, the audio context remains in a state that can't be reinitialized. Is there any way to resolve this?

**Comment by mrDIMAS** [comment]
Hi, this drop is simply calling `context.close()`. Am I right that this `context = new AudioContext()` fails for you after you've dropped the output device? In any case, I need more context - where are you trying to re-initialize the audio context (JS or Rust), what are your use case and so on.

**Comment by dustinbowers** [comment]
I've solved the issue I was having. It was my fault; the way I was reinitializing my WASM was actually skipping over the context cleanup
